// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onpaxrgbvthjiajstprq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ucGF4cmdidnRoamlhanN0cHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODQwOTMsImV4cCI6MjA1Mjk2MDA5M30.GH9W0q3-eAy3FcHD1wu45AXRiqEZo8qTXgy9M18mBsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);